* THE DESIGN AND IMPLEMENTATION OF METAOBJECT PROTOCOLS
** How CLOS is Implemented
*** A Subset of CLOS
*** Basic Backstage 
**** Example CLOS program
(defclass rectangle ()
     ((height :initform 0.0 :initarg :height)
      (width  :initform 0.0 :initarg :width)))

(defclass color-mixin ()
     ((cyan     :initform 0 :initarg :cyan)
      (magenta  :initform 0 :initarg :magenta)
      (yellow   :initform 0 :initarg :yellow)))

(defclass color-rectangle (color-mixin rectangle)
     ((clearp :initform (y-or-n-p "But is it transparent?")
              :initarg :clearp :accessor clearp)))

(defgeneric paint (x))

(defmethod paint ((x rectangle))                ;Method #1
  (vertical-stroke (slot-value x 'height)
                   (slot-value x 'width)))

(defmethod paint :before ((x color-mixin))      ;Method #2
  (set-brush-color (slot-value x 'cyan)
                   (slot-value x 'magenta)
		   (slot-value x 'yellow)))

(defmethod paint ((x color-rectangle))          ;Method #3
  (unless (clearp x) (call-next-method)))

(setq door
      (make-instance 'color-rectangle
        :width 38 :height 84 :cyan 60 :yellow 55 :clearp nil))

*** Representing Classes
The CLOS user defines classes with the =defclass= macro.

In the first step in the construction of Closette,
the class =standard-class= is defined to centralize
the description of what class metaobjects look like.

Instances of =standard-class= represent individual
classes; or, to say it another way, class metaobjects
are instances of =standard-class= .

Here is the definition of =standard-class=:

#+BEGIN_EXAMPLE
(defclass standard-class ()
  ((name :initarg :name
         :accessor class-name)
   (direct-superclasses :initarg :direct-superclasses
                                 :accessor class-direct-superclasses)
   (direct-slots :accessor class-direct-slots)
   (class-precedence-list :accessor class-precedence-list)
   (effective-slots :accessor class-slots)
   (direct-subclasses :initform ()
                      :accessor class-direct-subclasses)
   (direct-methods :initform ()
                   :accessor class-direct-methods)))
#+END_EXAMPLE

In Closette's three layered implementation structure, the
job of the =defclass= macro is to parse the class definition
and convert it into a call to =ensure-class=.

#+BEGIN_EXAMPLE
(defmacro defclass (name direct-superclasses direct-slots &rest options)
  `(ensure-class ',name
     :direct-superclasses ,(canonicalize-direct-superclasses
                             direct-superclasses)
     :direct-slots ,(canonicalize-direct-slots
	              direct-slots)
     ,@(canonicalize-defclass-options options)))
#+END_EXAMPLE

*** Printing Objects
*** Representing the Structure of Instances
*** Representing Generic Functions
*** Representing Methods
*** Invoking Generic Functions
*** A Word About Performance
*** Summary      
** Introspection and Analysis
*** Introducing Class Metaobjects
*** Browsing Classes
*** Browsing Generic Functions
*** Programmatic Creation of New Classes
*** Summary
** Extending the Language
*** Specialized Class Metaobjects
*** Terminology
*** Using Specialized Class Metaobject Classes
*** Class Precedence Lists
*** Slot Inheritance
*** Other Inheritance Protocols
*** Slot Access
*** Instance Allocation
*** Summary
** Protocol Design
*** A Simple Generic Function Invocation Protocol
*** Functional and Procedural Protocols
*** Layered Protocols
*** Improving Performance
*** Protocol Design Summary
* A METAOBJECT PROTOCOL FOR CLOS
** Concepts
*** Introduction
*** Metaobjects
*** Inheritance Structure of Metaobject Classes
*** Processing of the User Interface Macros
*** Subprotocols
** Generic Functions and Methods
* Appendices
** Introduction to CLOS
** Solutions
** Living with Circularity
** A Working Closette Implementation
*** Notes on the working Closette Implementation
**** Loading information
The /exports/ variable contains a list of the 
functions defined in Closette.

#+BEGIN_EXAMPLE
(defvar exports
  '((defclass defgeneric defmethod
     find-class class-of
     call-next-method next-method-p
     slot-value slot-boundp slot-exists-p slot-makunbound
     make-instance change-class
     initialize-instance reinitialize-instance shared-initialize
     update-instance-for-different-class
     print-object

     standard-object 
     standard-class standard-generic-function standard-method
     class-name
          
     class-direct-superclasses class-direct-slots
     class-precedence-list class-slots class-direct-subclasses
     class-direct-methods
     generic-function-name generic-function-lambda-list
     generic-function-methods generic-function-discriminating-function

     ...to be continued...)))
#+END_EXAMPLE


**** Utilities
**** Standard instances
**** Class metaobjects and standard-class
**** Generic function metaobjects and standard-generic functions
**** Method metaobjects and standard-method
**** Generic function invocation
**** Bootstrap
**** Methods having to do with class metaobjects
**** Methods having to do with generic function metaobjects
**** Methods having to do with method metaobjects
**** Methods having to do with generic function invocation
** Cross Reference to full MOP
* Commentary
The book is about a new approach to programming language design,
in which the two demands of elegance and efficiency are viewed
as compatible, not conflicting.

Metaobject protocols are interfaces to the language that 
give users the ability to incrementally modify the 
language's behavior and implementation, as well as the 
ability to write programs within the language.

Languages that incorportate metaobject protocols blur the
distinction between language designer and language user.

The metaobject protocol approach is based on the idea that
one can and should "open languages up", allowing users to
adjust the design and implementation to suit their 
particular needs.

If handled properly, opening up the language design need
not compromise program portability or implementation 
efficiency.

In a language based upon this MOP, the language implementation
itself is structured as an object-oriented program.

In effect, the resulting implementation does not represent
a single point in the overall space of language designs,
but rather an entire /region/ within that space.

The purpose of the book is two-fold:
- Part I gradually derives a simplified metaobject protocol for CLOS
- Part II provides a complete and detailed description of a particular MOP designed for CLOS

A running theme of the AMOP book is the
backstage/frontstage parts of design.

* Practice coding.

(defclass r ()
  ((h :initform 0.0 :initarg :h)
   (w :initform 0.0 :initarg :w)))

(defclass cm ()
  ((c :initform 0 :initarg :c)
   (m :initform 0 :initarg :m)
   (y :initform 0 :initarg :y)))

(defclass cr (cm r)
  ((clearp :initform (y-or-n-p "But is it transparent?")
           :initarg :clearp :accessor clearp)))

(defgeneric p (x))

(defmethod p ((x r))
  (vs (slot-value x 'height)
      (slot-value x 'width)))

(defmethod p :before ((x cm))
  (set-brush-color (slot-value x 'c)
                   (slot-value x 'm)
		   (slot-value x 'y)))

(defmethod p ((x cr))
  (unless (clearp x) (call-next-method)))

(setq d
      (make-instance 'cr
      :w 38 :h 84 :c 60 :y 55 :clearp nil))


(defclass rectangle ()
  ((height :initarg :start-height
           :initform 5
           :accessor rectangle-height)
   (width :initarg :start-width
          :initform 8
          :accessor rectangle-width)))

(setf r1 (make-instance 'rectangle :start-height 50 :start-width 100))
(setf r2 (make-instance 'rectangle :start-height 60 :start-width 100))
(setf r3 (make-instance 'rectangle :start-height 70 :start-width 100))


* Using CLOS to get a job
For the job seeker, the ultimate recursive solution is
to get a job using the thing that you were doing to get
the job.

So for instance, right now I am using org-mode and CLOS
to help me get a get a job. It would be ideal if I had
a job where I got to use org-mode/CLOS.

So we will make a list of companies that may be using
CLOS. 

(defclass company ()
  ((:name :email :location)))

(setq ravenbrook
  (make-instance 'company
    :ravenbrook
    :info@ravenbrook.com
    :england))

Actually, we can start with Ravenbrook as the 
prototype for our company class. 

At http://www.ravenbrook.com/contact/, we
have the following information.

Name:       Ravenbrook
E-Mail:     info@ravenbrook.com
Telephone:  [Long British number]
Fax:        [Long British number]
Post:       Cambridge, England
Location:   Google Maps Link

(ravenbrook info@ravenbrook.com england)

But I can use CLOS/org-mode anywhere, not
just in explicitly Common Lisp places. So
basically anywhere I could use the skills
developed here (and elsewhere).

The goal. Get a job in Boston or Providence.
Or figure out how to make money as a free-lancer.

(Mathworks)

That's enough about jobs right now. We can come
back to them later. 

* Code Examples
** Keene-1989
*** Triangles
The sources for this example are from pp. 67-74 and 145-150
**** Source: 67-74
#+BEGIN_EXAMPLE
; Defines three local slots and one shared slot
(defclass triangle (shape)
      ((side-a :accessor side-a :initarg :side-a)
       (side-b :accessor side-b :initarg :side-b)
       (side-c :accessor side-c :initarg :side-c)
       (number-of-sides :reader number-of-sides
                        :initform 3
                        :allocation :class)))

;;; Return the area of a triangle, given three sides.
;;; Algorithm is: area = ab(sin C)/2
(defun area-of-triangle (a b c)
  (let ((angle-C (three-sides-to-angle c a b)))
    (* a b (sin angle-C) .5)))

;;; Return the angle A between adjacent sides b and c
;;; and opposite side a, given all sides of a triangle
;;; Law of Cosines: a^2 = b^2 + c^2 - 2bc(cos A)
(defun three-sides-to-angle (a b c)
  (acos (/ (- (+ (expt b 2) (expt c 2))
              (expt a 2))
	   (* 2 b c))))

;;; Return the area of a triangle.
(defmethod area ((tri triangle))
  (area-of-triangle (side-a tri)
                    (side-b tri)
		    (side-c tri)))

;;; Defines a local slot that stores the area of each
;;; triangle and a reader method for the slot.
(defclass triangle (shape)
      ((side-a :accessor side-a :initarg :side-a)
       (side-b :accessor side-b :initarg :side-b)
       (side-c :accessor side-c :initarg :side-c)
       (number-of-sides :reader number-of-sides
                        :initform 3
                        :allocation :class)
       (area :reader area :initarg :area)))

;;; Defines a constructor which initializes the area
(defun make-triangle (side-a side-b side-c)
  (make-instance 'triangle
                 :side-a side-a
                 :side-b side-b
                 :side-c side-c
                 :area (area-of-triangle
                         side-a side-b side-c)))

(defmethod (setf side-a) :after (new-length (tri triangle))
  (setf (area tri)
        (area-of-triangle new-length
	                  (side-b tri)
			  (side-c tri))))

;;; Defining the reader side-a
(defmethod side-a ((tri triangle))
  (slot-value tri 'side-a))

;;; Defining the writer (setf side-a)
(defmethod (setf side-a) (new-side-a (tri triangle))
  (setf (slot-value tri 'side-a) new-side-a))

(defmethod angle-A ((tri triangle))
  (three-sides-to-angle (side-a tri)
                        (side-b tri)
			(side-c tri)))

(defmethod angle-A ((tri triangle))
  (with-accessors ((a side-a)
                   (b side-b)
		   (c side-c))
		   tri
     (three-sides-to-angle a b c)))

;;; Using slot-value to access the slots
(defmethod angle-A ((tri triangle))
  (three-sides-to-angle (slot-value tri 'side-a)
                        (slot-value tri 'side-b)
			(slot-value tri 'side-c)))

;;; Using with-slots to access the slots
(defmethod angle-A ((tri triangle))
  (with-slots (side-a side-b side-c)
              tri
    (three-sides-to-angle side-a side-b side-c)))
#+END_EXAMPLE
**** Source: 145-150
 #+BEGIN_EXAMPLE
(defclass shape () ()
  (:documentation "The foundation of all shapes."))

(defclass triangle (shape)
  ((a :reader side-a :initarg :side-a)
   (b :reader side-b :initarg :side-b)
   (c :reader side-c :initarg :side-c)))

(defun make-triangle (a b c)
  ;; All sides should be represented as floats
  (make-instance 'triangle :side-a (coerce a 'float)
                           :side-b (coerce b 'float)
                           :side-c (coerce c 'float)))

;;; Return the angle A between adjacent sides b and c
;;; and opposite side a, given all sides of a triangle
;;; Law of Cosines: a^2 = b^2 + c^2 - 2bc(cos A)
(defun three-sides-to-angle (a b c)
  (acos (/ (- (+ (expt b 2)
                 (expt c 2))
	      (expt a 2))
	   (* 2 b c))))

(defmethod angle-A ((tri triangle))
  (three-sides-to-angle
    (side-a tri) (side-b tri) (side-c tri)))

(defmethod angle-B ((tri triangle))
  (three-sides-to-angle
    (side-b tri) (side-c tri) (side-a tri)))

(defmethod angle-C ((tri triangle))
  (three-sides-to-angle
    (side-c tri) (side-a tri) (side-b tri)))

(defgeneric dimensions (shape)
  (:documentation "Returns list of side lengths."))

(defgeneric angles (shape)
  (:documentation "Returns list of angles."))

(defgeneric area (shape)
  (:documentation "Returns area of the shape."))

(defmethod dimensions ((tri triangle))
  (list (side-a tri)
        (side-b tri)
	(side-c tri)))

(defmethod angles ((tri triangle))
  (list (angle-A tri)
        (angle-B tri)
	(angle-C tri)))

;;; Return the area of a triangle
;;; Algorithm is: area = ab(sin C)/2
(defmethod area ((tri triangle))
  (* (side-a tri) (side-b tri)
     (sin (angle-C tri))
     .5))

(defclass triangle (shape)
  ((a :reader side-a :initarg :side-a)
   (b :reader side-b :initarg :side-b)
   (angle-C :reader angle-C :initarg :angle-C)))

;;; Here we delete slot c and add angle-C
;;; We need to initialize the new slot angle-C
(defmethod update-instance-for-redefined-class :after
           ((instance triangle)
	    added-slots discarded-slots
	    plist &rest initargs)
  (declare (ignore initargs))
  ;; Identify this particular redefinition
  (if (and (member 'c discarded-slots)
           (member 'angle-C added-slots))
      (setf (slot-value instance 'angle-C)
            (three-sides-to-angle
	      (getf plist 'c)
	      (side-a instance)
	      (side-b instance)))))

(defmethod side-c ((tri triangle)
  (third-side (side-a tri)
              (side-b tri)
	      (angle-C tri)))

;;; Algorithm is: c^2 = a^2 + b^2 - 2ab(cos C)
(defun third-side (a b angle-C)
  (sqrt (- (+ (expt a 2)
              (expt b 2))
	   (* 2 a b (cos angle-C)))))

(defun make-triangle (a b c)
  (let* ((float-a (coerce a 'float))
         (float-b (coerce b 'float))
	 (float-c (coerce c 'float))
	 (angle-C (three-sides-to-angle
	            float-c float-a float-b)))
    (make-instance 'triangle :side-a float-a
                             :side-b float-b
                             :angle-C angle-C)))
#+END_EXAMPLE

*** Installation
The source for this example is from pages 76-82
#+BEGIN_EXAMPLE
(defgeneric install (software-product operating-system)
  (:documentation "Installs software on the operating system."))

;;; Method 1
(defmethod install ((sw basic-product) (os basic-os))
  /body/)

;;; Method 2
(defmethod install ((sw basic-product) non-os)
  (error "Cannot install because ~A is not
          a recognized operating system." non-os))

;;; Method 3
(defmethod install (non-product (os basic-os))
  (error "Cannot install because ~A is not a
          recognized software product." non-product))

;;; Method 4
(defmethod install (non-product non-os)
  (error "Cannot install because ~A is not a
          recognized software product and ~A
	  is not a recognized operating system."
	  non-product non-os))
#+END_EXAMPLE

| Method   | Lambda-list                        |
|          |                                    |
| Method 1 | ((sw basic-product) (os basic-os)) |
| Method 2 | ((sw basic-product) non-os)        |
| Method 3 | (non-product (os basic-os))        |
| Method 4 | (non-product non-os)               |


#+BEGIN_EXAMPLE
;;; Here install is called with two valid arguments.
(install *life* *genera*)

;;; Method 1 is applicable because these forms are true.
(typep *life* 'basic-product)
(typep *genera* 'basic-os)

;;; Method 2 is applicable because these forms are true.
(typep *life* 'basic-product)
(typep *genera* 't)

;;; Method 3 is applicable because these forms are true.
(typep *life* 't)
(typep *genera* 'basic-os)

;;; Method 4 is applicable because these forms are true.
(typep *life* 't)
(typep *genera* 't)

;;; Implementation of Install
;;; We can implement install to call four generic functions

;;; Method 1
(defmethod install ((sw basic-product) (os basic-os))
  (restore-product sw os)
  (compile-product sw os)
  (configure-site  sw os)
  (verify-product  sw os))

(defmethod restore-product (sw (os genera)) /body/)
(defmethod restore-product (sw (os unix)) /body/)

(defgeneric get-source-pathname (product os)
  (:documentation "Returns a string."))

(defmethod get-source-pathname ((sw life) (os unix))
  "/bin/games/life.lisp")

(defmethod get-source-pathname ((sw adventure) (os unix))
  "/bin/games/adventure.lisp")

(defmethod get-source-pathname ((sw life) (os genera))
  "sys:games;life.lisp")

(defmethod get-source-pathname ((sw adventure) (os genera))
  "sys:games;adventure.lisp")  

(defmethod compile-product (sw os)
  (compile-file (get-source-pathname sw os)))

(defmethod configure-site ((sw life) (os genera)) body)
(defmethod configure-site ((sw adventure) (os genera)) body)
(defmethod configure-site ((sw life) (os unix)) body)
(defmethod configure-site ((sw adventure) (os unix)) body)

(defmethod verify-product ((sw life) os) body)
(defmethod verify-product ((sw adventure) os) body)
#+END_EXAMPLE

*** Locks
The source for this example is from pages 17-64
47 Pages of text 


